name: Two Sum

on:
  push:
    paths:
      - 'Problems/00001-00100/00001 Two Sum/**'
      - '!**.md'
  pull_request:
    paths:
      - 'Problems/00001-00100/00001 Two Sum/**'
      - '!**.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: 'Problems/00001-00100/00001 Two Sum'

      - name: Build the project
        run: dotnet build --configuration Release --no-restore
        working-directory: 'Problems/00001-00100/00001 Two Sum'

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: 'Problems/00001-00100/00001 Two Sum'