name: C# Solutions Test

on:
  push:
    branches: [main, problem/**/cs, problem/**/cs/**]
    paths:  ["src/csharp/**", "!**.md", "!.gitignore", "!.editorconfig" ]
  pull_request:
    branches: [main]
    paths:  ["src/csharp/**", "!**.md", "!.gitignore", "!.editorconfig" ]
  workflow_dispatch:

jobs:
  get-changed-paths:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^..HEAD src/csharp/ | grep -E '.*\.cs|.*\.csproj')
          echo "Changed files: $CHANGED_FILES"
          {
            echo "changed_files<<EOF"
            echo "$CHANGED_FILES"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Create problem paths matrix
        id: set-matrix
        run: |
          if [ -n "${{ steps.changed-files.outputs.changed_files }}" ]; then
            PROBLEM_PATHS=$(echo "${{ steps.changed-files.outputs.changed_files }}" | while IFS= read -r file; do
              if [ -n "$file" ] && [[ "$file" == *.csproj ]]; then
                dirname "$file"
              fi
            done | sort | uniq | jq -R -s -c 'split("\n") | map(select(. != ""))')
          else
            PROBLEM_PATHS="[]"
          fi
          echo "Problem paths: $PROBLEM_PATHS"
          echo "matrix={\"problem_paths\":${PROBLEM_PATHS}}" >> $GITHUB_OUTPUT

  build-and-test:
    needs: get-changed-paths
    runs-on: ubuntu-latest
    if: ${{ needs.get-changed-paths.outputs.matrix != '{"problem_paths":[]}' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-changed-paths.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ matrix.problem_paths }}

      - name: Build and test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ${{ matrix.problem_paths }}
